# Generated by Django 5.0.2 on 2024-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0003_player_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Current_club',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='Nationality',
            field=models.CharField(max_length=20),
        ),
    ]
